### PR TITLE
Fix legacy validatePasswords and add test for the legacy SecureHash

### PR DESCRIPTION
**Pull request by akovari**
I also updated the scala versions.

### CODE REVIEW

**Comment by nremond** [comment]
Looks good, thank you. 
Would you just explain me why your switched to `java.util.Arrays.equals`?

**Comment by akovari** [comment]
It is because `==` only compares arrays identity, so that they would have to be the same actual reference. To compare the contents of the array, you need to use `java.util.Arrays.equals `.
Without this, the `validatePasswords` always returns false, since 2 are actually different references, even though they might have the same contents.
You can find many articles about it.

Is there any chance you could release this into maven repos?
Thanks

**Comment by nremond** [comment]
I just did. But consider changing your implementation, the legacy implementation is really *legacy*

**Comment by nremond** [comment]
Well, Sonatype is down ... will release everything tomorrow if I can.

**Comment by nremond** [comment]
Version 0.6.2 ;-)

**Comment by akovari** [comment]
I already updated our code to use the new implementation to generate passwords but we still need to be able to validate old passwords.
Thanks for the release!

**Pull request merged**
